- hosts: localhost
  vars:
   host: "192.168.122.40"
   username: "admin"
   password: ""
   vdom: "root"
  tasks:
  - name: Configure group of Internet Service.
    fortios_firewall_internet-service-group:
      host:  "{{  host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{  vdom }}"
      firewall_internet-service-group:
        state: "present"
        comment: "Comment."
        member:
         -
            id:  "5 (source: firewall.internet-service.id)"
        name: "default_name_6"
