- hosts: localhost
  vars:
   host: "192.168.122.40"
   username: "admin"
   password: ""
   vdom: "root"
  tasks:
  - name: Configure IPv6 extension header filter.
    fortios_firewall_ipv6-eh-filter:
      host:  "{{  host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{  vdom }}"
      firewall_ipv6-eh-filter:
        state: "present"
        auth: "enable"
        dest-opt: "enable"
        fragment: "enable"
        hdopt-type: "6"
        hop-opt: "enable"
        no-next: "enable"
        routing: "enable"
        routing-type: "10"
