- hosts: localhost
  vars:
   host: "192.168.122.40"
   username: "admin"
   password: ""
   vdom: "root"
  tasks:
  - name: Configure local FortiGuard Web Filter local ratings.
    fortios_webfilter_ftgd-local-rating:
      host:  "{{  host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{  vdom }}"
      webfilter_ftgd-local-rating:
        state: "present"
        rating: "<your_own_value>"
        status: "enable"
        url: "http://myurl.com"
