- hosts: localhost
  vars:
   host: "192.168.122.40"
   username: "admin"
   password: ""
   vdom: "root"
  tasks:
  - name: Configure a forward server group consisting or multiple forward servers. Supports failover and load balancing.
    fortios_web-proxy_forward-server-group:
      host:  "{{  host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{  vdom }}"
      web-proxy_forward-server-group:
        state: "present"
        affinity: "enable"
        group-down-option: "block"
        ldb-method: "weighted"
        name: "default_name_6"
        server-list:
         -
            name: "default_name_8 (source: web-proxy.forward-server.name)"
            weight: "9"
