- hosts: localhost
  vars:
   host: "192.168.122.40"
   username: "admin"
   password: ""
   vdom: "root"
  tasks:
  - name: Configure network authentication type.
    fortios_wireless-controller.hotspot20_anqp-network-auth-type:
      host:  "{{  host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{  vdom }}"
      wireless-controller.hotspot20_anqp-network-auth-type:
        state: "present"
        auth-type: "acceptance-of-terms"
        name: "default_name_4"
        url: "http://myurl.com"
