- hosts: localhost
  vars:
   host: "192.168.122.40"
   username: "admin"
   password: ""
   vdom: "root"
  tasks:
  - name: Configure venue name duple.
    fortios_wireless-controller.hotspot20_anqp-venue-name:
      host:  "{{  host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{  vdom }}"
      wireless-controller.hotspot20_anqp-venue-name:
        state: "present"
        name: "default_name_3"
        value-list:
         -
            index: "5"
            lang: "<your_own_value>"
            value: "<your_own_value>"
