- hosts: localhost
  vars:
   host: "192.168.122.40"
   username: "admin"
   password: ""
   vdom: "root"
  tasks:
  - name: Configure network access identifier (NAI) realm.
    fortios_wireless-controller.hotspot20_anqp-nai-realm:
      host:  "{{  host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{  vdom }}"
      wireless-controller.hotspot20_anqp-nai-realm:
        state: "present"
        nai-list:
         -
            eap-method:
             -
                auth-param:
                 -
                    id:  "6"
                    index: "7"
                    val: "eap-identity"
                index: "9"
                method: "eap-identity"
            encoding: "disable"
            nai-realm: "<your_own_value>"
            name: "default_name_13"
        name: "default_name_14"
