- hosts: localhost
  vars:
   host: "192.168.122.40"
   username: "admin"
   password: ""
   vdom: "root"
  tasks:
  - name: Settings for WebTrends.
    fortios_log.webtrends_setting:
      host:  "{{  host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{  vdom }}"
      log.webtrends_setting:
        state: "present"
        server: "192.168.100.40"
        status: "enable"
