- hosts: localhost
  vars:
   host: "192.168.122.40"
   username: "admin"
   password: ""
   vdom: "root"
  tasks:
  - name: Configure MAC address tables.
    fortios_system_mac-address-table:
      host:  "{{  host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{  vdom }}"
      system_mac-address-table:
        state: "present"
        interface: "<your_own_value> (source: system.interface.name)"
        mac: "<your_own_value>"
        reply-substitute: "<your_own_value>"
