- hosts: localhost
  vars:
   host: "192.168.122.40"
   username: "admin"
   password: ""
   vdom: "root"
  tasks:
  - name: Configure sFlow.
    fortios_system_sflow:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      system_sflow:
        collector-ip: "<your_own_value>"
        collector-port: "4"
        source-ip: "84.230.14.43"
