- hosts: localhost
  vars:
   host: "192.168.122.40"
   username: "admin"
   password: ""
   vdom: "root"
  tasks:
  - name: Configure FortiClient registration synchronization settings.
    fortios_endpoint-control_forticlient-registration-sync:
      host:  "{{  host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{  vdom }}"
      endpoint-control_forticlient-registration-sync:
        state: "present"
        peer-ip: "<your_own_value>"
        peer-name: "<your_own_value>"
