- hosts: localhost
  vars:
   host: "192.168.122.40"
   username: "admin"
   password: ""
   vdom: "root"
  tasks:
  - name: Registered FortiClient list.
    fortios_endpoint-control_registered-forticlient:
      host:  "{{  host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{  vdom }}"
      endpoint-control_registered-forticlient:
        state: "present"
        flag: "3"
        ip: "<your_own_value>"
        mac: "<your_own_value>"
        reg-fortigate: "<your_own_value>"
        status: "7"
        uid: "<your_own_value>"
        vdom: "<your_own_value>"
