- hosts: localhost
  vars:
   host: "192.168.122.40"
   username: "admin"
   password: ""
   vdom: "root"
  tasks:
  - name: Configure a remote cache device as Web cache storage.
    fortios_wanopt_remote-storage:
      host:  "{{  host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{  vdom }}"
      wanopt_remote-storage:
        state: "present"
        local-cache-id: "<your_own_value>"
        remote-cache-id: "<your_own_value>"
        remote-cache-ip: "<your_own_value>"
        status: "disable"
