- hosts: localhost
  vars:
   host: "192.168.122.40"
   username: "admin"
   password: ""
   vdom: "root"
  tasks:
  - name: Configure FortiSwitch IGMP snooping global settings.
    fortios_switch-controller_igmp-snooping:
      host:  "{{  host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{  vdom }}"
      switch-controller_igmp-snooping:
        state: "present"
        aging-time: "3"
        flood-unknown-multicast: "enable"
