- hosts: localhost
  vars:
   host: "192.168.122.40"
   username: "admin"
   password: ""
   vdom: "root"
  tasks:
  - name: Configure global 802.1X settings.
    fortios_switch-controller_802-1X-settings:
      host:  "{{  host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{  vdom }}"
      switch-controller_802-1X-settings:
        state: "present"
        link-down-auth: "set-unauth"
        max-reauth-attempt: "4"
        reauth-period: "5"
