- hosts: localhost
  vars:
   host: "192.168.122.40"
   username: "admin"
   password: ""
   vdom: "root"
  tasks:
  - name: Configure FortiSwitch storm control.
    fortios_switch-controller_storm-control:
      host:  "{{  host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{  vdom }}"
      switch-controller_storm-control:
        state: "present"
        broadcast: "enable"
        rate: "4"
        unknown-multicast: "enable"
        unknown-unicast: "enable"
