- hosts: localhost
  vars:
   host: "192.168.122.40"
   username: "admin"
   password: ""
   vdom: "root"
  tasks:
  - name: Configure FortiSwitch LLDP settings.
    fortios_switch-controller_lldp-settings:
      host:  "{{  host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{  vdom }}"
      switch-controller_lldp-settings:
        state: "present"
        fast-start-interval: "3"
        management-interface: "internal"
        status: "enable"
        tx-hold: "6"
        tx-interval: "7"
