- hosts: localhost
  vars:
   host: "192.168.122.40"
   username: "admin"
   password: ""
   vdom: "root"
  tasks:
  - name: Configure system-wide switch controller settings.
    fortios_switch-controller_system:
      host:  "{{  host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{  vdom }}"
      switch-controller_system:
        state: "present"
        parallel-process: "3"
        parallel-process-override: "disable"
