- hosts: localhost
  vars:
   host: "192.168.122.40"
   username: "admin"
   password: ""
   vdom: "root"
  tasks:
  - name: Configure L2TP.
    fortios_vpn_l2tp:
      host:  "{{  host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{  vdom }}"
      vpn_l2tp:
        state: "present"
        eip: "<your_own_value>"
        enforce-ipsec: "enable"
        sip: "<your_own_value>"
        status: "enable"
        usrgrp: "<your_own_value> (source: user.group.name)"
